version: "3"

services:
  api:
    container_name: brasileiras-api
    image: ghcr.io/caio86/brasileiras-api
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: brasileiras-db
    image: mysql
    hostname: mysqldb
    restart: unless-stopped
    volumes:
      - br-db-data:/data
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: r2d2
      MYSQL_DATABASE: brasileiras_db
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-p$$MYSQL_ROOT_PASSWORD$$",
        ]
      timeout: 20s
      interval: 5s
      retries: 10

volumes:
  br-db-data:
